### ISSUE TITLE
Add ability to limit how many instances of the version number is affected

### ISSUE THREAD

**Issue by flyte** [inirudebwoy/bamp#27]
In our `pyproject.toml` file, the first instance of the version number should be bamped, but not any of the other requirement versions that happen to be the same.

Given the following `pyproject.toml` file:

```toml
[tool.poetry]
name = "micro"
version = "1.7.0"

[tool.poetry.dependencies]
python = "^3.9"
pydantic = "^1.10.4"
black = "^22.12.0"
click = "^8.1.7"

[tool.poetry.group.dev.dependencies]
ipdb = "^0.13.11"

[build-system]
requires = ["poetry-core>=1.7.0"]
build-backend = "poetry.core.masonry.api"
```

When you run a `bamp patch`, it will update the following two lines:

```toml
version = "1.7.1"

requires = ["poetry-core>=1.7.1"]
```

There should be either a configuration, or it should default to only affecting one instance of the version number.
